return {
    Boolean = { fg="#dca3a3" },
    Character = { fg="#dca3a3", bold=true },
    Comment = { fg="#7f9f7f" },
    Conditional = { fg="#f0dfaf", bold=true },
    Constant = { fg="#dca3a3", bold=true },
    Cursor = { fg="#000d18", bg="#8faf9f", bold=true },
    vCursor = { fg="#000d18", bg="#8faf9f", bold=true },
    iCursor = { fg="#000d18", bg="#8faf9f", bold=true },
    lCursor = { fg="#000d18", bg="#8faf9f", bold=true },
    Debug = { fg="#bca3a3", bold=true },
    Define = { fg="#ffcfaf", bold=true },
    Delimiter = { fg="#8f8f8f" },
    DiffAdd = { fg="#fbd3c7", bg="#3f3f3f", bold=true },
    DiffChange = { fg="#fbd3c7", bg="#3f3f3f", bold=true },
    DiffDelete = { fg="#fbd3c7", bg="#3f3f3f", bold=true },
    DiffText = { fg="#ecbcbc", bg="#41363c", bold=true },
    Directory = { fg="#9fafaf", bold=true },
    ErrorMsg = { fg="#80d4aa", bg="#2f2f2f", bold=true },
    Exception = { fg="#c3bf9f", bold=true },
    Float = { fg="#c0bed1" },
    FoldColumn = { fg="#93b3a3", bg="#3f4040" },
    Folded = { fg="#93b3a3", bg="#3f4040" },
    Function = { fg="#efef8f" },
    Identifier = { fg="#efdcbc" },
    IncSearch = { fg="#f8f893", bg="#385f38" },
    Keyword = { fg="#f0dfaf", bold=true },
    Macro = { fg="#ffcfaf", bold=true },
    ModeMsg = { fg="#ffcfaf"  },
    MoreMsg = { fg="#ffffff", bold=true },
    Number = { fg="#8cd0d3" },
    Operator = { fg="#f0efd0" },
    PmenuSbar = { fg="#000000", bg="#2e3330" },
    PmenuThumb = { fg="#040404", bg="#a0afa0"},
    PreCondit = { fg="#dfaf8f", bold=true },
    PreProc = { fg="#ffcfaf", bold=true },
    Question = { fg="#ffffff", bold=true },
    Repeat = { fg="#ffd7a7", bold=true },
    Search = { fg="#ffffe0", bg="#284f28" },
    SignColumn = { fg="#3f3f3f", bold=true },
    SpecialChar = { fg="#dca3a3", bold=true },
    SpecialComment = { fg="#cfbfaf" },
    SpecialKey = { fg="#9ece9e" },
    Statement = { fg="#e3ceab"  },
    StatusLine = { fg="#3f3f3f", bg="#9da4af" },
    StatusLineTerm = { fg="#3f3f3f", bg="#9da4af" },
    StatusLineNC = { fg="#2e3330", bg="#88b090" },
    StatusLineTermNC = { fg="#2e3330", bg="#88b090" },
    StorageClass = { fg="#c3bf9f", bold=true },
    String = { fg="#cc9393" },
    Structure = { fg="#efefaf", bold=true },
    Tag = { fg="#e89393", bold=true },
    Title = { fg="#efefef", bold=true },
    Todo = { fg="#dfdfdf", bold=true },
    Typedef = { fg="#dfe4cf", bold=true },
    Type = { fg="#dfdfbf", bold=true },
    VertSplit = { fg="#5d6262" },
    WarningMsg = { fg="#ffffff", bg="#333333", bold=true },
    WildMenu = { fg="#cbecd0", bg="#2c302d", underline=true },
    SpellBad = { sp="#bc6c4c", fg="#dc8c6c" },
    SpellCap = { sp="#6c6c9c", fg="#8c8cbc" },
    SpellRare = { sp="#bc6c9c", fg="#bc8cbc" },
    SpellLocal = { sp="#7cac7c", fg="#9ccc9c" },
    Normal = { fg="#dcdccc", bg="#3f3f3f" },
    EndOfBuffer = { fg="#dcdccc" },
    Terminal = { fg="#dcdccc", bg="#3f3f3f" },
    Conceal = { fg="#8f8f8f", bg="#484848" },
    ColorColumn = { bg="#484848" },
    CursorLine = { bg= "#434443" },
    CursorLineNr = { fg="#d2d39b", bg="#2f2f2f" },
    CursorColumn = { bg="#434343" },
    LineNr = { fg="#5d6262", bg="#353535" },
    NonText = { fg="#5d6262", bold=true },
    Pmenu = { bg="#383838", fg="#8f8f8f" },
    PmenuSel = { bg="#242424", fg="#d0d0a0", bold=true },
    MatchParen = { fg="#b2b2a0", bg="#2f2f2f", bold=true },
    TabLine = { fg="#d0d0b8", bg="#222222", bold=true },
    TabLineSel = { fg="#f0f0b0", bg="#333333", bold=true },
    TabLineFill = { fg="#dccdcc", bg="#101010", bold=true },
    Statusline = { bg="#3f3f3f" },
    Visual = { bg="#2f2f2f" },
    VisualNOS = { bg="#2f2f2f" },
    Error = { fg="#e37170", bg="#3d3535", bold=true },
    Include = { fg="#dfaf8f", bold=true },
    Label = { fg="#dfcfaf", underline=true },
}
